jQuery(document).ready(function(){$('form#contactForm button.submit').click(function(){$('#image-loader').fadeIn();var contactName=$('#contactForm #contactName').val();var contactEmail=$('#contactForm #contactEmail').val();var contactSubject=$('#contactForm #contactSubject').val();var contactMessage=$('#contactForm #contactMessage').val();var data='contactName='+contactName+'&contactEmail='+contactEmail+
'&contactSubject='+contactSubject+'&contactMessage='+contactMessage+'&page=contactform';$.ajax({type:"POST",url:"redirector.php",data:data,success:function(msg){if(msg.indexOf('OK')==-1){$('#image-loader').fadeOut();$('#message-warning').html(msg);$('#message-warning').fadeIn();}else{$('#image-loader').fadeOut();$('#message-warning').hide();$('#contactForm').fadeOut();$('#message-success').fadeIn();msg=msg.substring(2);setTimeout(function(){window.location="http://"+msg;},1500);}}});return false;});$('form#escrowform button.submit').click(function(){$('#image-loader').fadeIn();var buyeremail=$('#escrowform #buyeremail').val();var selleremail=$('#escrowform #selleremail').val();var btcaddress=$('#escrowform #btcaddress').val();var amount=$('#escrowform #amount').val();var amounttype=$('#escrowform #amounttype').val();var message=$('#escrowform #message').val();message=addslashes(encodeURIComponent(message));var bors=$('#escrowform #bors').val();var refer=$('#escrowform #refer').val();var fee=$('#escrowform #fee').val();var judge=$('#escrowform #judge').val();var goodsorservice=$('#escrowform #goodsorservice').val();var feesplit=$('#escrowform #feesplit').val();if(feesplit==""){feesplit="NULL"}
if(btcaddress==""){btcaddress="NULL"}
if(judge==""){judge="NULL"}
if(refer=="undefined"){refer=''}
if(amount.contains('&')){amount='NULL'}
var data='buyeremail='+buyeremail+'&selleremail='+selleremail+'&btcaddress='+btcaddress+'&amount='+amount+'&amounttype='+amounttype+'&message='+message+'&fee='+fee+'&judge='+judge+'&feesplit='+feesplit+'&goodsorservice='+goodsorservice+'&page=escrowform';if(refer!=""){data=data.concat('&refer='+refer)}
if(amounttype.substr(0,1)=="M"){var pubkeyone=$('#escrowform #pubkeyone').val();var pubkeytwo=$('#escrowform #pubkeytwo').val();data=data.concat('&pubkeyone='+pubkeyone+'&pubkeytwo='+pubkeytwo)}
$.ajax({type:"POST",url:"redirector.php",data:data,success:function(msg){if(msg.indexOf('OK')===-1){$('#image-loader').fadeOut();$('#message-warning').html(msg);$('#message-warning').fadeIn();}else{$('#image-loader').fadeOut();$('#message-warning').hide();$('#escrowform').fadeOut();$('#message-success').fadeIn();document.getElementById('buyeremailposter').value=document.getElementById('buyeremail').value;document.getElementById('selleremailposter').value=document.getElementById('selleremail').value;document.getElementById('sellerbitcoinaddressposter').value=document.getElementById('btcaddress').value;document.getElementById('amountposter').value=document.getElementById('amount').value;document.getElementById('amounttypeposter').value=document.getElementById('amounttype').value;document.getElementById('feepayerposter').value=document.getElementById('fee').value;document.getElementById('messageposter').value=document.getElementById('message').value;document.getElementById('borsposter').value=document.getElementById('bors').value;document.getElementById('judgeposter').value=document.getElementById('judge').value;document.getElementById('goodsorserviceposter').value=document.getElementById('goodsorservice').value;document.getElementById('feesplitposter').value=document.getElementById('feesplit').value;try{document.getElementById('pubkeyoneposter').value=document.getElementById('pubkeyone').value;document.getElementById('pubkeytwoposter').value=document.getElementById('pubkeytwo').value;}
catch(err){}
document.forms["posterform"].submit();}}});return false;});$('form#s1transactionstatus button.submit').click(function(){$('#image-loader').fadeIn();var transactionid=$('#s1transactionstatus #transactionid ').val();var bors=$('#s1transactionstatus #bors ').val();if(transactionid==''){transactionid='NULL'}
if(transactionid.indexOf('=')>0){transactionid='NULL1'}
if(transactionid.indexOf('&')>0){transactionid='NULL1'}
var data='transactionid='+transactionid+'&bors='+bors+'&page=ismultisig';$.ajax({type:"POST",url:"redirector.php",data:data,success:function(msg){if(msg.indexOf('ERROR')===-1){$('#image-loader').fadeOut();$('#message-warning').hide();$('#s1transactionstatus').fadeOut();if(bors=='v'||bors=='V'){$('#image-loader').fadeIn();$('#image-loader').fadeOut();$('#message-warning').hide();$('#s2transactionstatus').fadeOut();$('#message-success').fadeIn();document.getElementById('transactionidposter').value=document.getElementById('transactionid').value;document.getElementById('borsposter').value=document.getElementById('bors').value;document.forms["switchform"].submit();}else{if(msg.indexOf('false')===-1){$('#multisig').fadeIn();}else{$('#nonmultisig').fadeIn();}}}else{$('#image-loader').fadeOut();$('#message-warning').html(msg);$('#message-warning').fadeIn();}}});return false;});$("form#s2transactionstatus button.submit").click(function(e){e.preventDefault();});$('form#s2transactionstatus button.submit').click(function(){document.getElementById('transactionidposter').value=document.getElementById('transactionid').value;document.getElementById('borsposter').value=document.getElementById('bors').value;document.getElementById('secretcodeposter').value=document.getElementById('secretcode').value;document.getElementById('messageposter').value=document.getElementById('message').value;document.getElementById('signatureposter').value=document.getElementById('signature').value;$('#image-loader').fadeIn();$('#image-loader').fadeOut();$('#message-warning').hide();$('#s2transactionstatus').fadeOut();$('#message-success').fadeIn();document.forms["switchform"].submit().preventDefault();});$('form#referral button.submit').click(function(){$('#image-loader').fadeIn();var addy=$('#referral #addy ').val();var email=$('#referral #email ').val();if(email==''){email='NULL'}
if(addy==''){addy='NULL'}
var data='addy='+addy+'&email='+email+'&page=referral';$.ajax({type:"POST",url:"redirector.php",data:data,success:function(msg){if(msg.indexOf('OK')===-1){$('#image-loader').fadeOut();$('#message-warning').html(msg);$('#message-warning').fadeIn();}else{$('#image-loader').fadeOut();$('#message-warning').hide();$('#referral').fadeOut();$('#message-success').fadeIn();msg=msg.substring(2);setTimeout(function(){window.location="http://"+msg+"/refer.php?page=signingup&addy="+addy+'&email='+email;},500);}}});return false;});$('form#multisig button.submit').click(function(){$('#image-loader').fadeIn();var address1=$('#multisig #addy ').val();var address2=$('#multisig #email ').val();if(address1==''){address1='NULL'}
if(address2==''){address2='NULL'}
var data='address1='+address1+'&address2='+address2+'&page=multisig';$.ajax({type:"POST",url:"redirector.php",data:data,success:function(msg){if(msg.indexOf('OK')===-1){$('#image-loader').fadeOut();$('#message-warning').html(msg);$('#message-warning').fadeIn();}else{$('#image-loader').fadeOut();$('#message-warning').hide();$('#referral').fadeOut();$('#message-success').fadeIn();msg=msg.substring(2);setTimeout(function(){window.location="http://"+msg+"/refer.php?page=signingup&addy="+addy+'&email='+email;},500);}}});return false;});$('form#beta button.submit').click(function(){$('#image-loader').fadeIn();var email=$('#beta #email ').val();if(email==''){email='NULL'}
var data='email='+email+'&page=beta';$.ajax({type:"POST",url:"redirector.php",data:data,success:function(msg){if(msg.indexOf('OK')===-1){$('#image-loader').fadeOut();$('#message-warning').html(msg);$('#message-warning').fadeIn();}else{$('#image-loader').fadeOut();$('#message-warning').hide();$('#referral').fadeOut();$('#message-success').fadeIn();}}});return false;});$('form#judgesignup button.submit').click(function(){$('#image-loader').fadeIn();var email=$('#judgesignup #email ').val();var btcaddy=$('#judgesignup #address ').val();var name=$('#judgesignup #name ').val();var bitcoinpubkey=$('#judgesignup #bitcoinpubkey ').val();var nubitspubkey=$('#judgesignup #nubitspubkey ').val();if(email==''){email='NULL';}
if(btcaddy==''){btcaddy='NULL';}
if(name==''){name='NULL';}
var data='email='+email+'&name='+name+'&addy='+btcaddy+'&bitcoinpubkey='+bitcoinpubkey+'&nubitspubkey='+nubitspubkey+'&page=judgesignup';$.ajax({type:"POST",url:"redirector.php",data:data,success:function(msg){if(msg.indexOf('OK')===-1){$('#image-loader').fadeOut();$('#message-warning').html(msg);$('#message-warning').fadeIn();}else{$('#image-loader').fadeOut();$('#message-warning').hide();$('#referral').fadeOut();$('#message-success').fadeIn();document.getElementById('emailposter').value=document.getElementById('email').value;document.getElementById('bitcoinaddressposter').value=document.getElementById('address').value;document.getElementById('nameposter').value=document.getElementById('name').value;document.getElementById('bitcoinpubkeyposter').value=document.getElementById('bitcoinpubkey').value;document.getElementById('nubitspubkeyposter').value=document.getElementById('nubitspubkey').value;document.forms["judgesignupposter"].submit();}}});return false;});$('form#messaging button.submit').click(function(){$('#image-loader').fadeIn();var transaction=$('#messaging #transaction ').val();var bors=$('#messaging #BorS ').val();var secret=$('#messaging #secret ').val();var message=$('#messaging #message ').val();if(message==''){message='NULL'}else{message=addslashes(encodeURIComponent(message));}
var data='transaction='+transaction+'&bors='+bors+'&secret='+secret+'&message='+message+'&page=preparemessage';$.ajax({type:"POST",url:"redirector.php",data:data,success:function(msg){if(msg.indexOf('OK')===-1){$('#image-loader').fadeOut();$('#message-warning').html(msg);$('#message-warning').fadeIn();}else{$('#image-loader').fadeOut();$('#message-warning').hide();$('#messaging').fadeOut();$('#message-success').fadeIn();msg=msg.substring(2);setTimeout(function(){window.location="http://"+msg+"/transactionStatus.php?transaction="+transaction+'&bors='+bors+'&secret='+secret+'&message='+message+'&page=preparemessage';},500);}}});return false;});});function addslashes(str){return(str+'').replace(/[\\"']/g,'\\$&').replace(/\u0000/g,'\\0');}